version: '3.8'
services:
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "10251-10255:10251-10255"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=2
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    volumes:
      - cosmos-data:/data
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
  swa:
    image: ghcr.io/azure/static-web-apps-cli
    command: ["tail", "-f", "/dev/null"]
    tty: true
    ports:
      - "4280:4280"
    volumes:
      - .:/app
    working_dir: /app
volumes:
  cosmos-data:
  azurite-data:
