name: test and build

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop, feature/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/AstroForm.sln
      - name: Format Check
        run: dotnet format src/AstroForm.sln --verify-no-changes
      - name: Build
        run: dotnet build src/AstroForm.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/AstroForm.sln --configuration Release --collect:"XPlat Code Coverage" --results-directory TestResults --no-build
      - name: Generate Coverage Report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:CoverageReport -reporttypes:Cobertura
      - name: Coverage Check
        run: |
          FILE=CoverageReport/Cobertura.xml
          if [ -z "$FILE" ]; then
            echo "Coverage file not found." >&2
            exit 1
          fi
          RATE=$(grep -o 'line-rate="[0-9.]*"' "$FILE" | head -n1 | sed 's/line-rate="//;s/"//')
          echo "Coverage: $RATE"
          awk 'BEGIN{ if('$RATE' < 0.7) exit 1 }'
