name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore AstroForm.sln
      - name: Build
        run: dotnet build AstroForm.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test AstroForm.sln --no-build --verbosity normal
